### ISSUE TITLE
How did you make the skeuomorphic keys in the documentation?

### ISSUE THREAD

**Issue by alexiskattan** [OscarGodson/jKey#31]
I'm looking to do something similar and some advice would be great

**Comment by OscarGodson** [comment]
Nothing too crazy :) its been a long time since I looked at the CSS but I copied this from the CSS in the index.html file:

``` css
kbd {
        background:#eee;
        border-color:#ccc #aaa #888 #bbb;
        border-width:2px 4px 5px 3px;
        border-style:solid;
        color:#000;
        padding:3px 2px;
        white-space:nowrap;
        display:inline-block;
        min-width:25px;
        text-align:center;
        -webkit-box-shadow:rgba(0,0,0,0.5) 0 0 5px;
        -moz-box-shadow:rgba(0,0,0,0.5) 0 0 5px;
        box-shadow:rgba(0,0,0,0.5) 0 0 5px;
        position:relative;
        font-family:helvetica,arial,sans-serif;
        text-shadow:none;
      }
      kbd:hover {-webkit-box-shadow:rgba(0,0,0,0.75) 0 0 5px;top:1px;}
```

then just use like `<kbd>enter</kbd>`
